### ISSUE TITLE
Implement area selection feature

### ISSUE THREAD

**Issue by mizvol** [Axeln78/Axeln78.github.io#1]
Allow users to select a subgraph or an area in the graph. Once selected, display activity of the subgraph in the line chart below.

Example: [Select nodes in an area](https://github.com/jacomyal/sigma.js/issues/252)

**Comment by Axeln78** [comment]
So I did a neighbour selection in the end. If you click on the single Node button it turns into multi - node and enables neighbour selection. 
Though they are not kept in memory from on to the other because it becomes very messy on the plot side.
All of this can be changed of course!

**Comment by mizvol** [comment]
Is there any way to assign different colors to different lines in the line chart?

**Comment by Axeln78** [comment]
It's not built in but I'll do it quickly, I've already researched it!

**Comment by mizvol** [comment]
Once this is done, we can close the issue.
