### ISSUE TITLE
Scroll bar artifacts in modal windows

### ISSUE THREAD

**Issue by mizvol** [Axeln78/Axeln78.github.io#12]
There are redundant scroll bars appearing in modal windows.
See screenshot for more details.
![Scroll bar artifacts screenshot](https://user-images.githubusercontent.com/9719707/57130766-e07a1880-6d9a-11e9-9fbb-f6ce482e2374.png)

**Comment by Axeln78** [comment]
Okay, this one I know why I even think I might have changed it. But It does not appear on mac

**Comment by Axeln78** [comment]
Should have been fixed, could you double check?

**Comment by mizvol** [comment]
Fixed.
