### ISSUE TITLE
Implement time-range filter

### ISSUE THREAD

**Issue by mizvol** [Axeln78/Axeln78.github.io#4]
Time-range filter should take the range from a Plotly graph. Then, it should send the selected range to the Sigma graph. A node in the Sigma graph should be displayed only if the value of a time-series attribute of the node is above a threshold. The threshold should be chosen by the users (using a text box, for example).

Use Sigma filter plugin to implement it.

**Comment by Axeln78** [comment]
So this is independent from the "selection" of nodes right? This should show the changes all across the graph?

**Comment by mizvol** [comment]
Selection of nodes is a separate feature, yes. This one replaces the slider
basically.

On the other hand, if it's easier to implement it as an independent slider
(not related to plotly) to select a time-range, it'd work as a silution
too.

The point of this feature is to select a time range and display only those
nodes that have a non-zero time-series value during that range.

Le mer. 27 mars 2019 à 15:32, Axel Nilsson <notifications@github.com> a
écrit :
