### ISSUE TITLE
Edge length filtering not working properly!

### ISSUE THREAD

**Issue by Axeln78** [Axeln78/Axeln78.github.io#6]

**Comment by Axeln78** [comment]
It would be cool if the filter could be relative to the camera view, this way they would appear when one would zoom in. 
-> do the filtering at every re-scale
-> adapt to camera size

**Comment by mizvol** [comment]
@TODO remove the feature from the view.

Not implemented. Low priority issue. 

Closing the issue since we have too many features on the same view and it may be confusing for users.

**Comment by Axeln78** [comment]
Hey, I actually fixed it! it's up now!
