### ISSUE TITLE
Add a spinner for time-consuming requests

### ISSUE THREAD

**Issue by mizvol** [Axeln78/Axeln78.github.io#7]
When loading large files or calling computationally expensive functions (e.g. noverlap or layout), show a spinner while waiting.

Example: [https://spin.js.org/](https://spin.js.org/)

**Comment by Axeln78** [comment]
The spinner is implemented but more tests need to be done to make sure that it is properly visible

**Comment by Axeln78** [comment]
The spinner now runs when the graph loads and during the whole initialisation phase. It should also be visible when the Noverlap is running but it is not for some reason :/

**Comment by Axeln78** [comment]
Did you get the opportunity to look at this?

**Comment by mizvol** [comment]
There is a problem with asynchronous requests. Spinner function should be a callback. Alternatively, you can also use JS promises.

**Comment by mizvol** [comment]
This should help: [https://codepen.io/mitchlamers/pen/YNaqmV](https://codepen.io/mitchlamers/pen/YNaqmV)

**Comment by Axeln78** [comment]
This should be fixed now
