### ISSUE TITLE
Save graph as a GEXF file

### ISSUE THREAD

**Issue by mizvol** [Axeln78/Axeln78.github.io#8]
Users may want to explore graph and compute statistics using other tools. It would be nice to be able to export the graph as a file (e.g. GEXF).

Plugin: [sigma.exporters.gexf](https://github.com/Linkurious/linkurious.js/tree/develop/plugins/sigma.exporters.gexf)

**Comment by Axeln78** [comment]
I thought to make a modal where the user can choose between different formats
https://www.w3schools.com/howto/howto_css_modals.asp

**Comment by mizvol** [comment]
Yes. Since we already have SVG export, a modal allowing users to choose between GEXF and SVG is a good idea.

**Comment by Axeln78** [comment]
Have you used this plugin yourself before?

**Comment by Axeln78** [comment]
Basically it now works but exports all of the nodes and their colour. So you cannot export a GEXF file of a downsampled graph (by the filters)

**Comment by mizvol** [comment]
This is expected. The entire graph should be saved, not a filtered subgraph.

Issue can be closed.

Le sam. 27 avr. 2019 à 11:34, Axel Nilsson <notifications@github.com> a
écrit :
